// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Monetra.Infra.Data.Context;

#nullable disable

namespace Monetra.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251230203948_CreateInitial.2")]
    partial class CreateInitial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Monetra.Domain.BackOffice.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("Pk_customer_id");

                    b.HasIndex("UserId");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("Monetra.Domain.BackOffice.Entities.Mark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("DATETIME");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("DATETIME");

                    b.Property<decimal>("TargetAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("MONEY");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Mark", (string)null);
                });

            modelBuilder.Entity("Monetra.Domain.BackOffice.Entities.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("DATETIME");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR");

                    b.Property<bool>("Visible")
                        .HasColumnType("BIT");

                    b.HasKey("Id")
                        .HasName("Pk_Portofolio_Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Portfolio", (string)null);
                });

            modelBuilder.Entity("Monetra.Domain.BackOffice.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("MONEY");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<Guid>("PortfolioId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId1");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("Monetra.Domain.BackOffice.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id")
                        .HasName("Pk_User_Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Monetra.Domain.BackOffice.Entities.Customer", b =>
                {
                    b.HasOne("Monetra.Domain.BackOffice.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Monetra.Domain.BackOffice.Entities.Mark", b =>
                {
                    b.HasOne("Monetra.Domain.BackOffice.Entities.Customer", "Customer")
                        .WithOne("Mark")
                        .HasForeignKey("Monetra.Domain.BackOffice.Entities.Mark", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Monetra.Domain.BackOffice.Entities.Portfolio", b =>
                {
                    b.HasOne("Monetra.Domain.BackOffice.Entities.Customer", "Customer")
                        .WithMany("Portfolios")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Monetra.Domain.BackOffice.ObjectValues.Investment", "FixedIncome", b1 =>
                        {
                            b1.Property<Guid>("PortfolioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("MONEY");

                            b1.HasKey("PortfolioId");

                            b1.ToTable("Portfolio");

                            b1.WithOwner()
                                .HasForeignKey("PortfolioId");
                        });

                    b.OwnsOne("Monetra.Domain.BackOffice.ObjectValues.Investment", "VariableIncome", b1 =>
                        {
                            b1.Property<Guid>("PortfolioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("MONEY");

                            b1.HasKey("PortfolioId");

                            b1.ToTable("Portfolio");

                            b1.WithOwner()
                                .HasForeignKey("PortfolioId");
                        });

                    b.Navigation("Customer");

                    b.Navigation("FixedIncome")
                        .IsRequired();

                    b.Navigation("VariableIncome")
                        .IsRequired();
                });

            modelBuilder.Entity("Monetra.Domain.BackOffice.Entities.Transaction", b =>
                {
                    b.HasOne("Monetra.Domain.BackOffice.Entities.Portfolio", "Portfolio")
                        .WithMany("Transactions")
                        .HasForeignKey("PortfolioId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Monetra.Domain.BackOffice.Entities.User", b =>
                {
                    b.OwnsOne("Monetra.Domain.BackOffice.ObjectValues.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(170)
                                .HasColumnType("VARCHAR");

                            b1.HasKey("UserId");

                            b1.HasIndex("Address")
                                .IsUnique()
                                .HasDatabaseName("UX_User_Email");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("Monetra.Domain.BackOffice.Entities.Customer", b =>
                {
                    b.Navigation("Mark")
                        .IsRequired();

                    b.Navigation("Portfolios");
                });

            modelBuilder.Entity("Monetra.Domain.BackOffice.Entities.Portfolio", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
